version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Run linters
          command: yarn lint

      - run:
          name: Build website
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then \
              WEBSITE_ROOT_URL=https://sva.pscanf.com/ yarn build \
            ; else \
              WEBSITE_ROOT_URL=https://sva.pscanf.com/_/$CIRCLE_BRANCH/ yarn build \
            ; fi

      - run:
          name: Install staticdeploy cli
          command: |
            yarn global add @staticdeploy/cli
            echo 'export PATH=$PATH:$(yarn global bin)' >> $BASH_ENV

      - run:
          name: Create website bundle
          command: staticdeploy bundle

      - run:
          name: Deploy website bundle
          command: staticdeploy deploy

      - run:
          name: Purge CDN cache
          command: yarn purgeCdnCache
